(define (problem P1)
(:domain chibi-casa)
(:objects R1 R2 R3 R4 CHIBI1)
(:init (In R2)
        (kitchen R2)
        (livingroom R1)
        (garden R3)
        (bin-in R4)
        (clean R3)
        (clean R1)
        (family-hungry)
        (fish-hungry)
        (= (battery-capacity CHIBI1) 100)
        (= (inventory-space CHIBI1) 10)
        (= (item-capacity CHIBI1) 10)
        (= (recharge-rate CHIBI1) 2)
        (= (battery-amount CHIBI1) 40)
        (= (plants-garden R3) 5)
        (= (litter-in-room R4) 9)
        (= (litter-in-room R2) 4)
        (= (litter-in-room R1) 6)
	(= (total-cost CHIBI1) 0)
)

(:goal  (and
          (not (fish-hungry))
          (not (family-hungry))
          (= (litter-in-room R4) 0)
          (= (litter-in-room R1) 0)
          (clean R2)
          (clean R4)
          (= (plants-garden R3) 0)
          (= (litter-in-room R2) 0)
          (In R3)
 )
)
)
